### ISSUE TITLE
Commas break syntax highlighting

### ISSUE THREAD

**Issue by Alain1405** [textmate/yaml.tmbundle#1]
How to reproduce:
1) Create a new document;
2) Copy paste the following:
    OK: "I''m a single line string, everything is fine if I''m double quoted"
    Bug1: I''m a single line string, comma screws syntax highlighting without double quotes
    Bug2: "I''m a multiple lines string,
    comma breaks syntax highlighting with or without quotes"
3) Select Yaml syntax highlighting

Commas break syntax highlighting in multiline strings or in not quoted single line strings.
Attached a screenshot of the issue.
![screen shot 2014-02-03 at 18 47 07](https://f.cloud.github.com/assets/2998545/2067444/42341d40-8cfb-11e3-8928-d435746f44f1.png)

**Comment by infininight** [comment]
This has been corrected in 953d955b8247a784ed18bb27f5236408dfae0c1b.
