### ISSUE TITLE
My YAML is just monochrome green. Is this correct?

### ISSUE THREAD

**Issue by joelouthan** [textmate/yaml.tmbundle#14]
Am I doing something wrong?
![textmate2-yaml-2016-03-29_15-34-27](https://cloud.githubusercontent.com/assets/8844984/14122989/c7c4eb82-f5c3-11e5-9bcb-d9cda4ff245c.png)

**Comment by infininight** [comment]
The color depends on your active theme. The YAML grammar matches a lot of items in that example as a string so I presume your theme colors those as green.
