### ISSUE TITLE
Colon in | text block

### ISSUE THREAD

**Issue by aeschli** [textmate/yaml.tmbundle#19]
_From @almays on February 20, 2017 21:28_

I have yaml files with texts.
Texts can be multiline, include markdown. I screen out the texts with `|` thing.
```
En: |
  Some text: continuation of the text. 
```
In this case `Some text` is colorized as a key. But actually due to `|` it is going to be parsed as part of the text.

Yaml2json converter, for example, interpretes this syntax as expected:
```
{
  "En": "Some text: continuation of the text. \n"
}
```

But yaml colorizer mistakenly takes `:` in this case as key/value delimiter.

_Copied from original issue: Microsoft/vscode#20959_

**Comment by SaschaNaz** [comment]
I think this is the same issue with #17, no?

**Comment by aeschli** [comment]
Yes, looks like a duplicate of #17
