### ISSUE TITLE
Folded lines aren't highlighted correctly

### ISSUE THREAD

**Issue by aroben** [textmate/yaml.tmbundle#5]
Long lines are typically folded in YAML. They aren't getting highlighted correctly:

<img src="https://cloud.githubusercontent.com/assets/917945/5147951/5836fa1e-7188-11e4-9269-ac6e3b799454.png" height=95>

This test file was generated via the following:

```sh-session
$ ruby -ryaml -e 'puts YAML.dump({:desc => "hello hello hello " * 10})' > test.yml
```

**Comment by infininight** [comment]
This has been corrected in 953d955b8247a784ed18bb27f5236408dfae0c1b.
